Algoritmo "contar_1_a_10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/07/2024
Var
contador : inteiro


Inicio
 contador := 1
          enquanto contador <=10 faca
 escreva(contador)
 contador := contador + 1
 fimenquanto

Fimalgoritmo