Algoritmo "verificar_maioridade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/07/2024
Var
 idade: inteiro



Inicio
  Escreval ("Digite a sua idade: ")
  Leia(idade)
  se idade >= 18 entao
  escreval("Você é maior de idade")
  senao
  escreval("Você é menor de idade")
  fimse

Fimalgoritmo