Algoritmo "VerificarParImpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/07/2024
Var
   numero: inteiro
   
   


Inicio
    escreva ("Digite um número: ")
    leia(numero)
    
    se (numero % 2 = 0) então
    escreva("O numero é par, ")
    fimse

Fimalgoritmo