Algoritmo "Verificartemperatura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/07/2024
Var
    temperatura:  real
   


Inicio
     escreva("Digite a temperatura em °C ")
     leia(temperatura)
     
     se (temperatura > 0) entao
     escreva("A temperatura está aciam do ponto de congelamento.")
     fimse

Fimalgoritmo