Algoritmo "VerificarPositivo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/07/2024
Var
 numero: real
   
   


Inicio
   escreva("Digite um número: ")
   leia(numero)
   
   se (numero > 0) então
   escreva("O número é positivo.")
   fimse

Fimalgoritmo