Algoritmo "NOMES"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/07/2024
Var
NOMES: VETOR[1..3] DE CARACTERE
I: INTEIRO


Inicio
NOMES[1] <- "EDUARDO"
NOMES[2] <- "FERNANDA"
NOMES[3] <- "NICOLAS"

PARA I DE 1 ATE 3 FACA
     ESCREVA(NOMES[I], " ")
     FIMPARA


Fimalgoritmo